version: 0.2

phases:
  build:
    commands:
      - echo Build started on `date`
      - make release
  post_build:
    commands:
      - echo Build completed on `date`
artifacts:
  files:
    - release.tar.gz
