name: build
on: [push]

jobs:
  build:
    name: build
    # This job runs on Linux
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: Run make
        run: make
      - name: Upload math result for job 1
        uses: actions/upload-artifact@v1
        with:
          name: artifacts__test_ghaction
          path: release.tgz
